# Generated by Django 5.1.6 on 2025-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="market",
            field=models.CharField(default="F", max_length=10),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="type",
            field=models.CharField(default="stock", max_length=10),
        ),
    ]
